// README.txt for instructors. Ported from scorm-export-manager.js
// generateInstructorReadme (~line 1415), genericised and deterministic
// (generation date injected via opts.dateString, or derived from opts.isoDate).

import { resolveConfig } from "./config.js";

// YYYY-MM-DD -> DD/MM/YYYY. Reformatted by slicing rather than via `new Date()`,
// because parsing an ISO date yields UTC midnight and toLocaleDateString would
// then shift it a day back west of Greenwich — which would make the "pinned"
// date depend on the machine's timezone, defeating the point of pinning it.
function formatIsoDate(isoDate) {
  if (typeof isoDate !== "string" || !/^\d{4}-\d{2}-\d{2}/.test(isoDate)) return null;
  return `${isoDate.slice(8, 10)}/${isoDate.slice(5, 7)}/${isoDate.slice(0, 4)}`;
}

export function generateReadme(metadata = {}, opts = {}) {
  const config = resolveConfig(opts.config);
  const title = metadata.title || "Accessible Document";
  // Precedence: an explicit display string, then the package-wide isoDate pin,
  // then today. Without the isoDate arm the README embeds the wall-clock date and
  // is the one file in the package that cannot be reproduced.
  const dateString =
    opts.dateString || formatIsoDate(opts.isoDate) || new Date().toLocaleDateString("en-GB");
  const reportScore = opts.reportScore === true;
  const maxScore = Number.isFinite(opts.maxScore) ? opts.maxScore : 100;

  // Step 6 differs by whether this package reports a quiz score. A scored quiz
  // needs grading ENABLED and a Maximum score set at import (immutable later); a
  // content-only package should have scoring switched off.
  const gradingSteps = reportScore
    ? `6. Enable grading (Important): Leave the "Mark Score" checkbox TICKED.
   - Set "Grade using" to Score.
   - Set the Maximum score to ${maxScore} (this CANNOT be changed after import —
     to change it you must delete the package and re-import).
   - The quiz reports a normalised score, which Blackboard scales to this maximum.
7. Verify first: Pre-test in SCORM Cloud (cloud.scorm.com, free tier), run a pass
   and a fail attempt and confirm the score in the debug log, then import to a
   Blackboard test course and confirm the value in the gradebook via Student Preview.
8. Review description: Check the auto-generated description and adjust as needed.
9. Save: Click the "Save" button when ready`
    : `6. Disable scoring (Important): Scroll halfway down and UNTICK the "Mark Score" checkbox
   (This removes unnecessary deadline/scoring options since there's no assessment)
7. Review description: Check the auto-generated description and adjust to your preferences
8. Save: Click the "Save" button when ready`;

  return `SCORM Package: ${title}
Generated: ${dateString}
${config.PRODUCT_NAME}

SCORM VERSION: ${config.VERSION}
MATHJAX MODE: ${(opts.mathjaxMode || config.MATHJAX_MODE).toUpperCase()}
ASSESSMENT: ${reportScore ? `Scored quiz — reports to the gradebook (Maximum score ${maxScore})` : "None — content only"}

QUICK START: UPLOADING TO BLACKBOARD ULTRA
===========================================
1. In your Blackboard course: Click the Add button (+ icon)
2. From the menu: Select "Create"
3. Choose content type: Select "SCORM Package"
4. Upload file: Choose this SCORM ZIP file
5. Ignore the warning: Blackboard may show "Some issues were found" - this is normal
${gradingSteps}

UPLOADING TO OTHER LMS SYSTEMS
===============================
- Moodle: Course settings -> Add an activity -> SCORM package
- Canvas: Modules -> Add Item -> External Tool -> Upload SCORM
- Most LMS: Look for "SCORM", "Content Package", or "IMS Package" options
- Always select SCORM 2004 3rd Edition when prompted for version

ACCESSIBILITY FEATURES
======================
- WCAG 2.2 AA compliance
- Screen reader support (JAWS, NVDA, VoiceOver)
- MathJax context menus for mathematical navigation
- Keyboard navigation throughout all content
- High contrast themes (light/dark modes)
- Adjustable typography and reading tools
- Mathematical expression explorer

TECHNICAL REQUIREMENTS
======================
- Modern browser with JavaScript enabled
- MathJax CDN access recommended (current mode: ${opts.mathjaxMode || config.MATHJAX_MODE})
- Responsive design works on mobile/tablet/desktop
- No additional plugins required

TROUBLESHOOTING
===============
- "Some issues found" warning in Blackboard: Safe to ignore, content will work correctly
- Mathematical expressions not rendering: Ensure JavaScript is enabled and MathJax is accessible
- Accessibility features not working: Check that assistive technology is compatible with modern JavaScript

Generated by ${config.PRODUCT_NAME}
Designed for university STEM education with an accessibility-first approach`;
}
